### ISSUE TITLE
maven doesn't include quattor-ant.xml in the jar file

### ISSUE THREAD

**Issue by jrha** [quattor/scdb-ant-utils#12]
Without this, the tasks cannot be used.

**Comment by jouvin** [comment]
Are you sure? It should be a recent problem, I always used the jar file to update our installatioin and this is also what is used in `create-vanilla-SCDB.sh`. Can you give more information on the context?

**Comment by jrha** [comment]
The last release of the tasks was March 2013, the port to Maven was done May 2013, so it's probably been like this for at least three years. As far as context goes, just build a fresh checkout from the current master. Also the version seems to be wrong, it looks like the `pom.xml` was a copy-and-paste from the Pan repository? Perhaps you have a branch that never got merged?

```
# jar tf /home/jrha/src/jrha/scdb-ant-utils/target/scdb-ant-utils-10.0.0-SNAPSHOT.jar
META-INF/
META-INF/MANIFEST.MF
org/
org/quattor/
org/quattor/ant/
org/quattor/ant/VOConfigTask$VOMSServerCertificate.class
org/quattor/ant/RepositoryTask$Repository.class
org/quattor/ant/SvnCacheTask.class
org/quattor/ant/VOConfigTask$VOMSFqan.class
org/quattor/ant/VOConfigTask$VOMSServer.class
org/quattor/ant/ProfileInfoTask.class
org/quattor/ant/RepositoryTask.class
org/quattor/ant/VOConfigTask$VOMSEndpoint.class
org/quattor/ant/VOConfigTask$VOConfig.class
org/quattor/ant/ShowVersion.class
org/quattor/ant/NotifyClientTask.class
org/quattor/ant/VOConfigTask$VOCardHandler.class
org/quattor/ant/VOConfigTask$AccountPrefixConflict.class
org/quattor/ant/SvnTagTask.class
org/quattor/ant/SvnTagTask$StatusHandler.class
org/quattor/ant/VOConfigTask$1.class
org/quattor/ant/VOConfigTask.class
META-INF/maven/
META-INF/maven/org.quattor.ant/
META-INF/maven/org.quattor.ant/scdb-ant-utils/
META-INF/maven/org.quattor.ant/scdb-ant-utils/pom.xml
META-INF/maven/org.quattor.ant/scdb-ant-utils/pom.properties
```

**Comment by jouvin** [comment]
Ah yes, you are right! I did this a while ago, if I am right but I am not sure it has been really used. It used to be managed by `ant` and `ant package` probably still works properly.

**Comment by jrha** [comment]
Well no, because the `build.xml` was also deleted.

**Comment by jouvin** [comment]
It's bad then! I'll try to have a look...

**Comment by jrha** [comment]
I think I've got it mostly figured out, I'll open a PR in a minute.

**Comment by jouvin** [comment]
Even better!
