### ISSUE TITLE
FindBugs Bug Detector Report

### ISSUE THREAD

**Issue by jrha** [quattor/scdb-ant-utils#14]
These are the issues found by the latest run of findbugs against head, I couldn't figure out an easy way to convert each to a GitHub issue, so I copy-pasted the report, sorry.

<h2><a name="FindBugs_Bug_Detector_Report"></a>FindBugs Bug Detector Report</h2>

<p>The following document contains the results of <a class="externalLink" href="http://findbugs.sourceforge.net">FindBugs</a></p>

<p>FindBugs Version is <i>3.0.1</i></p>

<p>Threshold is <i>medium</i></p>

<p>Effort is <i>min</i></p></div>

<div class="section">
<h2><a name="Summary"></a>Summary</h2>
<table border="0" class="bodyTable">
<tr class="a">
<th>Classes</th>
<th>Bugs</th>
<th>Errors</th>
<th>Missing Classes</th></tr>
<tr class="b">
<td>17</td>
<td>35</td>
<td>0</td>
<td>0</td></tr></table></div>

<div class="section">

<h2><a name="Files"></a>Files</h2>

<table border="0" class="bodyTable">
<tr class="a">
<th>Class</th>
<th>Bugs</th></tr>
<tr class="b">
<td><a href="#org.quattor.ant.NotifyClientTask">org.quattor.ant.NotifyClientTask</a></td>
<td>2</td></tr>
<tr class="a">
<td><a href="#org.quattor.ant.ProfileInfoTask">org.quattor.ant.ProfileInfoTask</a></td>
<td>3</td></tr>
<tr class="b">
<td><a href="#org.quattor.ant.RepositoryTask">org.quattor.ant.RepositoryTask</a></td>
<td>3</td></tr>
<tr class="a">
<td><a href="#org.quattor.ant.RepositoryTask$Repository">org.quattor.ant.RepositoryTask$Repository</a></td>
<td>2</td></tr>
<tr class="b">
<td><a href="#org.quattor.ant.SvnCacheTask">org.quattor.ant.SvnCacheTask</a></td>
<td>1</td></tr>
<tr class="a">
<td><a href="#org.quattor.ant.SvnTagTask">org.quattor.ant.SvnTagTask</a></td>
<td>1</td></tr>
<tr class="b">
<td><a href="#org.quattor.ant.VOConfigTask">org.quattor.ant.VOConfigTask</a></td>
<td>5</td></tr>
<tr class="a">
<td><a href="#org.quattor.ant.VOConfigTask$AccountPrefixConflict">org.quattor.ant.VOConfigTask$AccountPrefixConflict</a></td>
<td>2</td></tr>
<tr class="b">
<td><a href="#org.quattor.ant.VOConfigTask$VOCardHandler">org.quattor.ant.VOConfigTask$VOCardHandler</a></td>
<td>3</td></tr>
<tr class="a">
<td><a href="#org.quattor.ant.VOConfigTask$VOConfig">org.quattor.ant.VOConfigTask$VOConfig</a></td>
<td>3</td></tr>
<tr class="b">
<td><a href="#org.quattor.ant.VOConfigTask$VOMSEndpoint">org.quattor.ant.VOConfigTask$VOMSEndpoint</a></td>
<td>1</td></tr>
<tr class="a">
<td><a href="#org.quattor.ant.VOConfigTask$VOMSServer">org.quattor.ant.VOConfigTask$VOMSServer</a></td>
<td>6</td></tr>
<tr class="b">
<td><a href="#org.quattor.ant.VOConfigTask$VOMSServerCertificate">org.quattor.ant.VOConfigTask$VOMSServerCertificate</a></td>
<td>3</td></tr></table></div><a name="org.quattor.ant.NotifyClientTask"></a>
<div class="section">
<h3><a name="org.quattor.ant.NotifyClientTask"></a>org.quattor.ant.NotifyClientTask</h3>
<table border="0" class="bodyTable">
<tr class="a">
<th>Bug</th>
<th>Category</th>
<th>Details</th>
<th>Line</th>
<th>Priority</th></tr>
<tr class="b">
<td>Unread field: org.quattor.ant.NotifyClientTask.version; should this field be static?</td>
<td>PERFORMANCE</td>
<td><a class="externalLink" href="http://findbugs.sourceforge.net/bugDescriptions.html#SS_SHOULD_BE_STATIC">SS_SHOULD_BE_STATIC</a></td>
<td>38</td>
<td>Medium</td></tr>
<tr class="a">
<td>org.quattor.ant.NotifyClientTask.execute() makes inefficient use of keySet iterator instead of entrySet iterator</td>
<td>PERFORMANCE</td>
<td><a class="externalLink" href="http://findbugs.sourceforge.net/bugDescriptions.html#WMI_WRONG_MAP_ITERATOR">WMI_WRONG_MAP_ITERATOR</a></td>
<td>69</td>
<td>Medium</td></tr></table></div><a name="org.quattor.ant.ProfileInfoTask"></a>
<div class="section">
<h3><a name="org.quattor.ant.ProfileInfoTask"></a>org.quattor.ant.ProfileInfoTask</h3>
<table border="0" class="bodyTable">
<tr class="b">
<th>Bug</th>
<th>Category</th>
<th>Details</th>
<th>Line</th>
<th>Priority</th></tr>
<tr class="a">
<td>Found reliance on default encoding in org.quattor.ant.ProfileInfoTask.execute(): new java.io.OutputStreamWriter(OutputStream)</td>
<td>I18N</td>
<td><a class="externalLink" href="http://findbugs.sourceforge.net/bugDescriptions.html#DM_DEFAULT_ENCODING">DM_DEFAULT_ENCODING</a></td>
<td>98</td>
<td>High</td></tr>
<tr class="b">
<td>Possible null pointer dereference in org.quattor.ant.ProfileInfoTask.execute() due to return value of called method</td>
<td>STYLE</td>
<td><a class="externalLink" href="http://findbugs.sourceforge.net/bugDescriptions.html#NP_NULL_ON_SOME_PATH_FROM_RETURN_VALUE">NP_NULL_ON_SOME_PATH_FROM_RETURN_VALUE</a></td>
<td>83</td>
<td>Medium</td></tr>
<tr class="a">
<td>Unread field: org.quattor.ant.ProfileInfoTask.version; should this field be static?</td>
<td>PERFORMANCE</td>
<td><a class="externalLink" href="http://findbugs.sourceforge.net/bugDescriptions.html#SS_SHOULD_BE_STATIC">SS_SHOULD_BE_STATIC</a></td>
<td>32</td>
<td>Medium</td></tr></table></div><a name="org.quattor.ant.RepositoryTask"></a>
<div class="section">
<h3><a name="org.quattor.ant.RepositoryTask"></a>org.quattor.ant.RepositoryTask</h3>
<table border="0" class="bodyTable">
<tr class="b">
<th>Bug</th>
<th>Category</th>
<th>Details</th>
<th>Line</th>
<th>Priority</th></tr>
<tr class="a">
<td>Found reliance on default encoding in org.quattor.ant.RepositoryTask.execute(): new java.io.FileWriter(String, boolean)</td>
<td>I18N</td>
<td><a class="externalLink" href="http://findbugs.sourceforge.net/bugDescriptions.html#DM_DEFAULT_ENCODING">DM_DEFAULT_ENCODING</a></td>
<td>132</td>
<td>High</td></tr>
<tr class="b">
<td>Found reliance on default encoding in org.quattor.ant.RepositoryTask.parseTemplate(File): new java.io.FileReader(File)</td>
<td>I18N</td>
<td><a class="externalLink" href="http://findbugs.sourceforge.net/bugDescriptions.html#DM_DEFAULT_ENCODING">DM_DEFAULT_ENCODING</a></td>
<td>259</td>
<td>High</td></tr>
<tr class="a">
<td>Unread field: org.quattor.ant.RepositoryTask.version; should this field be static?</td>
<td>PERFORMANCE</td>
<td><a class="externalLink" href="http://findbugs.sourceforge.net/bugDescriptions.html#SS_SHOULD_BE_STATIC">SS_SHOULD_BE_STATIC</a></td>
<td>46</td>
<td>Medium</td></tr></table></div><a name="org.quattor.ant.RepositoryTaskRepository"></a>
<div class="section">
<h3><a name="org.quattor.ant.RepositoryTaskRepository"></a>org.quattor.ant.RepositoryTask$Repository</h3>
<table border="0" class="bodyTable">
<tr class="b">
<th>Bug</th>
<th>Category</th>
<th>Details</th>
<th>Line</th>
<th>Priority</th></tr>
<tr class="a">
<td>Found reliance on default encoding in org.quattor.ant.RepositoryTask$Repository.parseURL(Map): new java.io.InputStreamReader(InputStream)</td>
<td>I18N</td>
<td><a class="externalLink" href="http://findbugs.sourceforge.net/bugDescriptions.html#DM_DEFAULT_ENCODING">DM_DEFAULT_ENCODING</a></td>
<td>519</td>
<td>High</td></tr>
<tr class="b">
<td>Found reliance on default encoding in org.quattor.ant.RepositoryTask$Repository.write(): new java.io.FileWriter(File)</td>
<td>I18N</td>
<td><a class="externalLink" href="http://findbugs.sourceforge.net/bugDescriptions.html#DM_DEFAULT_ENCODING">DM_DEFAULT_ENCODING</a></td>
<td>456</td>
<td>High</td></tr></table></div><a name="org.quattor.ant.SvnCacheTask"></a>
<div class="section">
<h3><a name="org.quattor.ant.SvnCacheTask"></a>org.quattor.ant.SvnCacheTask</h3>
<table border="0" class="bodyTable">
<tr class="a">
<th>Bug</th>
<th>Category</th>
<th>Details</th>
<th>Line</th>
<th>Priority</th></tr>
<tr class="b">
<td>Unread field: org.quattor.ant.SvnCacheTask.version; should this field be static?</td>
<td>PERFORMANCE</td>
<td><a class="externalLink" href="http://findbugs.sourceforge.net/bugDescriptions.html#SS_SHOULD_BE_STATIC">SS_SHOULD_BE_STATIC</a></td>
<td>50</td>
<td>Medium</td></tr></table></div><a name="org.quattor.ant.SvnTagTask"></a>
<div class="section">
<h3><a name="org.quattor.ant.SvnTagTask"></a>org.quattor.ant.SvnTagTask</h3>
<table border="0" class="bodyTable">
<tr class="a">
<th>Bug</th>
<th>Category</th>
<th>Details</th>
<th>Line</th>
<th>Priority</th></tr>
<tr class="b">
<td>Unread field: org.quattor.ant.SvnTagTask.version; should this field be static?</td>
<td>PERFORMANCE</td>
<td><a class="externalLink" href="http://findbugs.sourceforge.net/bugDescriptions.html#SS_SHOULD_BE_STATIC">SS_SHOULD_BE_STATIC</a></td>
<td>62</td>
<td>Medium</td></tr></table></div><a name="org.quattor.ant.VOConfigTask"></a>
<div class="section">
<h3><a name="org.quattor.ant.VOConfigTask"></a>org.quattor.ant.VOConfigTask</h3>
<table border="0" class="bodyTable">
<tr class="a">
<th>Bug</th>
<th>Category</th>
<th>Details</th>
<th>Line</th>
<th>Priority</th></tr>
<tr class="b">
<td>Found reliance on default encoding in org.quattor.ant.VOConfigTask.writeDNList(String): new java.io.FileWriter(String)</td>
<td>I18N</td>
<td><a class="externalLink" href="http://findbugs.sourceforge.net/bugDescriptions.html#DM_DEFAULT_ENCODING">DM_DEFAULT_ENCODING</a></td>
<td>378</td>
<td>High</td></tr>
<tr class="a">
<td>Found reliance on default encoding in org.quattor.ant.VOConfigTask.writeVOList(String): new java.io.FileWriter(String)</td>
<td>I18N</td>
<td><a class="externalLink" href="http://findbugs.sourceforge.net/bugDescriptions.html#DM_DEFAULT_ENCODING">DM_DEFAULT_ENCODING</a></td>
<td>354</td>
<td>High</td></tr>
<tr class="b">
<td>Unread field: org.quattor.ant.VOConfigTask.version; should this field be static?</td>
<td>PERFORMANCE</td>
<td><a class="externalLink" href="http://findbugs.sourceforge.net/bugDescriptions.html#SS_SHOULD_BE_STATIC">SS_SHOULD_BE_STATIC</a></td>
<td>66</td>
<td>Medium</td></tr>
<tr class="a">
<td>Unread public/protected field: org.quattor.ant.VOConfigTask.legacySuffixAlgorithm</td>
<td>STYLE</td>
<td><a class="externalLink" href="http://findbugs.sourceforge.net/bugDescriptions.html#URF_UNREAD_PUBLIC_OR_PROTECTED_FIELD">URF_UNREAD_PUBLIC_OR_PROTECTED_FIELD</a></td>
<td>101</td>
<td>Medium</td></tr>
<tr class="b">
<td>Unread public/protected field: org.quattor.ant.VOConfigTask.siteParamsTplNS</td>
<td>STYLE</td>
<td><a class="externalLink" href="http://findbugs.sourceforge.net/bugDescriptions.html#URF_UNREAD_PUBLIC_OR_PROTECTED_FIELD">URF_UNREAD_PUBLIC_OR_PROTECTED_FIELD</a></td>
<td>78</td>
<td>Medium</td></tr></table></div><a name="org.quattor.ant.VOConfigTaskAccountPrefixConflict"></a>
<div class="section">
<h3><a name="org.quattor.ant.VOConfigTaskAccountPrefixConflict"></a>org.quattor.ant.VOConfigTask$AccountPrefixConflict</h3>
<table border="0" class="bodyTable">
<tr class="a">
<th>Bug</th>
<th>Category</th>
<th>Details</th>
<th>Line</th>
<th>Priority</th></tr>
<tr class="b">
<td>org.quattor.ant.VOConfigTask$AccountPrefixConflict.toString() concatenates strings using + in a loop</td>
<td>PERFORMANCE</td>
<td><a class="externalLink" href="http://findbugs.sourceforge.net/bugDescriptions.html#SBSC_USE_STRINGBUFFER_CONCATENATION">SBSC_USE_STRINGBUFFER_CONCATENATION</a></td>
<td>1385</td>
<td>Medium</td></tr>
<tr class="a">
<td>Should org.quattor.ant.VOConfigTask$AccountPrefixConflict be a _static_ inner class?</td>
<td>PERFORMANCE</td>
<td><a class="externalLink" href="http://findbugs.sourceforge.net/bugDescriptions.html#SIC_INNER_SHOULD_BE_STATIC">SIC_INNER_SHOULD_BE_STATIC</a></td>
<td>1366</td>
<td>Medium</td></tr></table></div><a name="org.quattor.ant.VOConfigTaskVOCardHandler"></a>
<div class="section">
<h3><a name="org.quattor.ant.VOConfigTaskVOCardHandler"></a>org.quattor.ant.VOConfigTask$VOCardHandler</h3>
<table border="0" class="bodyTable">
<tr class="b">
<th>Bug</th>
<th>Category</th>
<th>Details</th>
<th>Line</th>
<th>Priority</th></tr>
<tr class="a">
<td>Dead store to hostname in org.quattor.ant.VOConfigTask$VOCardHandler.endElement(String, String, String)</td>
<td>STYLE</td>
<td><a class="externalLink" href="http://findbugs.sourceforge.net/bugDescriptions.html#DLS_DEAD_LOCAL_STORE">DLS_DEAD_LOCAL_STORE</a></td>
<td>560</td>
<td>Medium</td></tr>
<tr class="b">
<td>Comparison of String objects using == or != in org.quattor.ant.VOConfigTask$VOCardHandler.endElement(String, String, String) </td>
<td>BAD_PRACTICE</td>
<td><a class="externalLink" href="http://findbugs.sourceforge.net/bugDescriptions.html#ES_COMPARING_STRINGS_WITH_EQ">ES_COMPARING_STRINGS_WITH_EQ</a></td>
<td>535</td>
<td>Medium</td></tr>
<tr class="a">
<td>Comparison of String objects using == or != in org.quattor.ant.VOConfigTask$VOCardHandler.endElement(String, String, String) </td>
<td>BAD_PRACTICE</td>
<td><a class="externalLink" href="http://findbugs.sourceforge.net/bugDescriptions.html#ES_COMPARING_STRINGS_WITH_EQ">ES_COMPARING_STRINGS_WITH_EQ</a></td>
<td>526</td>
<td>Medium</td></tr></table></div><a name="org.quattor.ant.VOConfigTaskVOConfig"></a>
<div class="section">
<h3><a name="org.quattor.ant.VOConfigTaskVOConfig"></a>org.quattor.ant.VOConfigTask$VOConfig</h3>
<table border="0" class="bodyTable">
<tr class="b">
<th>Bug</th>
<th>Category</th>
<th>Details</th>
<th>Line</th>
<th>Priority</th></tr>
<tr class="a">
<td>Found reliance on default encoding in org.quattor.ant.VOConfigTask$VOConfig.writeVOTemplate(String): new java.io.FileWriter(String)</td>
<td>I18N</td>
<td><a class="externalLink" href="http://findbugs.sourceforge.net/bugDescriptions.html#DM_DEFAULT_ENCODING">DM_DEFAULT_ENCODING</a></td>
<td>756</td>
<td>High</td></tr>
<tr class="b">
<td>org.quattor.ant.VOConfigTask$VOConfig.toString() concatenates strings using + in a loop</td>
<td>PERFORMANCE</td>
<td><a class="externalLink" href="http://findbugs.sourceforge.net/bugDescriptions.html#SBSC_USE_STRINGBUFFER_CONCATENATION">SBSC_USE_STRINGBUFFER_CONCATENATION</a></td>
<td>740</td>
<td>Medium</td></tr>
<tr class="a">
<td>org.quattor.ant.VOConfigTask$VOConfig.writeVOTemplate(String) makes inefficient use of keySet iterator instead of entrySet iterator</td>
<td>PERFORMANCE</td>
<td><a class="externalLink" href="http://findbugs.sourceforge.net/bugDescriptions.html#WMI_WRONG_MAP_ITERATOR">WMI_WRONG_MAP_ITERATOR</a></td>
<td>784</td>
<td>Medium</td></tr></table></div><a name="org.quattor.ant.VOConfigTaskVOMSEndpoint"></a>
<div class="section">
<h3><a name="org.quattor.ant.VOConfigTaskVOMSEndpoint"></a>org.quattor.ant.VOConfigTask$VOMSEndpoint</h3>
<table border="0" class="bodyTable">
<tr class="b">
<th>Bug</th>
<th>Category</th>
<th>Details</th>
<th>Line</th>
<th>Priority</th></tr>
<tr class="a">
<td>Should org.quattor.ant.VOConfigTask$VOMSEndpoint be a _static_ inner class?</td>
<td>PERFORMANCE</td>
<td><a class="externalLink" href="http://findbugs.sourceforge.net/bugDescriptions.html#SIC_INNER_SHOULD_BE_STATIC">SIC_INNER_SHOULD_BE_STATIC</a></td>
<td>803</td>
<td>Medium</td></tr></table></div><a name="org.quattor.ant.VOConfigTaskVOMSServer"></a>
<div class="section">
<h3><a name="org.quattor.ant.VOConfigTaskVOMSServer"></a>org.quattor.ant.VOConfigTask$VOMSServer</h3>
<table border="0" class="bodyTable">
<tr class="b">
<th>Bug</th>
<th>Category</th>
<th>Details</th>
<th>Line</th>
<th>Priority</th></tr>
<tr class="a">
<td>Found reliance on default encoding in org.quattor.ant.VOConfigTask$VOMSServer.setOldCert(String): new java.util.Scanner(File)</td>
<td>I18N</td>
<td><a class="externalLink" href="http://findbugs.sourceforge.net/bugDescriptions.html#DM_DEFAULT_ENCODING">DM_DEFAULT_ENCODING</a></td>
<td>958</td>
<td>High</td></tr>
<tr class="b">
<td>Found reliance on default encoding in org.quattor.ant.VOConfigTask$VOMSServer.updateVOMSServerTemplate(String): new java.io.FileWriter(String)</td>
<td>I18N</td>
<td><a class="externalLink" href="http://findbugs.sourceforge.net/bugDescriptions.html#DM_DEFAULT_ENCODING">DM_DEFAULT_ENCODING</a></td>
<td>1035</td>
<td>High</td></tr>
<tr class="a">
<td>Redundant nullcheck of certValue, which is known to be non-null in org.quattor.ant.VOConfigTask$VOMSServer.setOldCert(String)</td>
<td>STYLE</td>
<td><a class="externalLink" href="http://findbugs.sourceforge.net/bugDescriptions.html#RCN_REDUNDANT_NULLCHECK_OF_NONNULL_VALUE">RCN_REDUNDANT_NULLCHECK_OF_NONNULL_VALUE</a></td>
<td>975</td>
<td>Medium</td></tr>
<tr class="b">
<td>Format string should use %n rather than \n in org.quattor.ant.VOConfigTask$VOMSServer.writeCertInfo(FileWriter)</td>
<td>BAD_PRACTICE</td>
<td><a class="externalLink" href="http://findbugs.sourceforge.net/bugDescriptions.html#VA_FORMAT_STRING_USES_NEWLINE">VA_FORMAT_STRING_USES_NEWLINE</a></td>
<td>1084</td>
<td>Medium</td></tr>
<tr class="a">
<td>Format string should use %n rather than \n in org.quattor.ant.VOConfigTask$VOMSServer.writeCertInfo(FileWriter)</td>
<td>BAD_PRACTICE</td>
<td><a class="externalLink" href="http://findbugs.sourceforge.net/bugDescriptions.html#VA_FORMAT_STRING_USES_NEWLINE">VA_FORMAT_STRING_USES_NEWLINE</a></td>
<td>1086</td>
<td>Medium</td></tr>
<tr class="b">
<td>Format string should use %n rather than \n in org.quattor.ant.VOConfigTask$VOMSServer.writeCertInfo(FileWriter)</td>
<td>BAD_PRACTICE</td>
<td><a class="externalLink" href="http://findbugs.sourceforge.net/bugDescriptions.html#VA_FORMAT_STRING_USES_NEWLINE">VA_FORMAT_STRING_USES_NEWLINE</a></td>
<td>1085</td>
<td>Medium</td></tr></table></div><a name="org.quattor.ant.VOConfigTaskVOMSServerCertificate"></a>
<div class="section">
<h3><a name="org.quattor.ant.VOConfigTaskVOMSServerCertificate"></a>org.quattor.ant.VOConfigTask$VOMSServerCertificate</h3>
<table border="0" class="bodyTable">
<tr class="a">
<th>Bug</th>
<th>Category</th>
<th>Details</th>
<th>Line</th>
<th>Priority</th></tr>
<tr class="b">
<td>Found reliance on default encoding in new org.quattor.ant.VOConfigTask$VOMSServerCertificate(VOConfigTask, String): String.getBytes()</td>
<td>I18N</td>
<td><a class="externalLink" href="http://findbugs.sourceforge.net/bugDescriptions.html#DM_DEFAULT_ENCODING">DM_DEFAULT_ENCODING</a></td>
<td>1109</td>
<td>High</td></tr>
<tr class="a">
<td>org.quattor.ant.VOConfigTask$VOMSServerCertificate.ldapDN(String) concatenates strings using + in a loop</td>
<td>PERFORMANCE</td>
<td><a class="externalLink" href="http://findbugs.sourceforge.net/bugDescriptions.html#SBSC_USE_STRINGBUFFER_CONCATENATION">SBSC_USE_STRINGBUFFER_CONCATENATION</a></td>
<td>1158</td>
<td>Medium</td></tr>
<tr class="b">
<td>Should org.quattor.ant.VOConfigTask$VOMSServerCertificate be a _static_ inner class?</td>
<td>PERFORMANCE</td>
<td><a class="externalLink" href="http://findbugs.sourceforge.net/bugDescriptions.html#SIC_INNER_SHOULD_BE_STATIC">SIC_INNER_SHOULD_BE_STATIC</a></td>
<td>1098</td>
<td>Medium</td></tr></table>

**Comment by jrha** [comment]
After some hacking around, I'm now down to the following...

<table border="0" class="bodyTable">
<tr class="a">
<th>Classes</th>
<th>Bugs</th>
<th>Errors</th>
<th>Missing Classes</th></tr>
<tr class="b">
<td>17</td>
<td>10</td>
<td>0</td>
<td>0</td></tr></table></div>
<div class="section">
<h2><a name="Files"></a>Files</h2>
<table border="0" class="bodyTable">
<tr class="a">
<th>Class</th>
<th>Bugs</th></tr>
<tr class="b">
<td><a href="#org.quattor.ant.NotifyClientTask">org.quattor.ant.NotifyClientTask</a></td>
<td>1</td></tr>
<tr class="a">
<td><a href="#org.quattor.ant.ProfileInfoTask">org.quattor.ant.ProfileInfoTask</a></td>
<td>1</td></tr>
<tr class="b">
<td><a href="#org.quattor.ant.VOConfigTask">org.quattor.ant.VOConfigTask</a></td>
<td>2</td></tr>
<tr class="a">
<td><a href="#org.quattor.ant.VOConfigTask$AccountPrefixConflict">org.quattor.ant.VOConfigTask$AccountPrefixConflict</a></td>
<td>1</td></tr>
<tr class="b">
<td><a href="#org.quattor.ant.VOConfigTask$VOCardHandler">org.quattor.ant.VOConfigTask$VOCardHandler</a></td>
<td>1</td></tr>
<tr class="a">
<td><a href="#org.quattor.ant.VOConfigTask$VOConfig">org.quattor.ant.VOConfigTask$VOConfig</a></td>
<td>1</td></tr>
<tr class="b">
<td><a href="#org.quattor.ant.VOConfigTask$VOMSEndpoint">org.quattor.ant.VOConfigTask$VOMSEndpoint</a></td>
<td>1</td></tr>
<tr class="a">
<td><a href="#org.quattor.ant.VOConfigTask$VOMSServer">org.quattor.ant.VOConfigTask$VOMSServer</a></td>
<td>1</td></tr>
<tr class="b">
<td><a href="#org.quattor.ant.VOConfigTask$VOMSServerCertificate">org.quattor.ant.VOConfigTask$VOMSServerCertificate</a></td>
<td>1</td></tr></table></div><a name="org.quattor.ant.NotifyClientTask"></a>
<div class="section">
<h3><a name="org.quattor.ant.NotifyClientTask"></a>org.quattor.ant.NotifyClientTask</h3>
<table border="0" class="bodyTable">
<tr class="a">
<th>Bug</th>
<th>Category</th>
<th>Details</th>
<th>Line</th>
<th>Priority</th></tr>
<tr class="b">
<td>org.quattor.ant.NotifyClientTask.execute() makes inefficient use of keySet iterator instead of entrySet iterator</td>
<td>PERFORMANCE</td>
<td><a class="externalLink" href="http://findbugs.sourceforge.net/bugDescriptions.html#WMI_WRONG_MAP_ITERATOR">WMI_WRONG_MAP_ITERATOR</a></td>
<td>69</td>
<td>Medium</td></tr></table></div><a name="org.quattor.ant.ProfileInfoTask"></a>
<div class="section">
<h3><a name="org.quattor.ant.ProfileInfoTask"></a>org.quattor.ant.ProfileInfoTask</h3>
<table border="0" class="bodyTable">
<tr class="a">
<th>Bug</th>
<th>Category</th>
<th>Details</th>
<th>Line</th>
<th>Priority</th></tr>
<tr class="b">
<td>Possible null pointer dereference in org.quattor.ant.ProfileInfoTask.execute() due to return value of called method</td>
<td>STYLE</td>
<td><a class="externalLink" href="http://findbugs.sourceforge.net/bugDescriptions.html#NP_NULL_ON_SOME_PATH_FROM_RETURN_VALUE">NP_NULL_ON_SOME_PATH_FROM_RETURN_VALUE</a></td>
<td>84</td>
<td>Medium</td></tr></table></div><a name="org.quattor.ant.VOConfigTask"></a>
<div class="section">
<h3><a name="org.quattor.ant.VOConfigTask"></a>org.quattor.ant.VOConfigTask</h3>
<table border="0" class="bodyTable">
<tr class="a">
<th>Bug</th>
<th>Category</th>
<th>Details</th>
<th>Line</th>
<th>Priority</th></tr>
<tr class="b">
<td>Unread public/protected field: org.quattor.ant.VOConfigTask.legacySuffixAlgorithm</td>
<td>STYLE</td>
<td><a class="externalLink" href="http://findbugs.sourceforge.net/bugDescriptions.html#URF_UNREAD_PUBLIC_OR_PROTECTED_FIELD">URF_UNREAD_PUBLIC_OR_PROTECTED_FIELD</a></td>
<td>109</td>
<td>Medium</td></tr>
<tr class="a">
<td>Unread public/protected field: org.quattor.ant.VOConfigTask.siteParamsTplNS</td>
<td>STYLE</td>
<td><a class="externalLink" href="http://findbugs.sourceforge.net/bugDescriptions.html#URF_UNREAD_PUBLIC_OR_PROTECTED_FIELD">URF_UNREAD_PUBLIC_OR_PROTECTED_FIELD</a></td>
<td>86</td>
<td>Medium</td></tr></table></div><a name="org.quattor.ant.VOConfigTaskAccountPrefixConflict"></a>
<div class="section">
<h3><a name="org.quattor.ant.VOConfigTaskAccountPrefixConflict"></a>org.quattor.ant.VOConfigTask$AccountPrefixConflict</h3>
<table border="0" class="bodyTable">
<tr class="b">
<th>Bug</th>
<th>Category</th>
<th>Details</th>
<th>Line</th>
<th>Priority</th></tr>
<tr class="a">
<td>Should org.quattor.ant.VOConfigTask$AccountPrefixConflict be a _static_ inner class?</td>
<td>PERFORMANCE</td>
<td><a class="externalLink" href="http://findbugs.sourceforge.net/bugDescriptions.html#SIC_INNER_SHOULD_BE_STATIC">SIC_INNER_SHOULD_BE_STATIC</a></td>
<td>1380</td>
<td>Medium</td></tr></table></div><a name="org.quattor.ant.VOConfigTaskVOCardHandler"></a>
<div class="section">
<h3><a name="org.quattor.ant.VOConfigTaskVOCardHandler"></a>org.quattor.ant.VOConfigTask$VOCardHandler</h3>
<table border="0" class="bodyTable">
<tr class="b">
<th>Bug</th>
<th>Category</th>
<th>Details</th>
<th>Line</th>
<th>Priority</th></tr>
<tr class="a">
<td>Dead store to hostname in org.quattor.ant.VOConfigTask$VOCardHandler.endElement(String, String, String)</td>
<td>STYLE</td>
<td><a class="externalLink" href="http://findbugs.sourceforge.net/bugDescriptions.html#DLS_DEAD_LOCAL_STORE">DLS_DEAD_LOCAL_STORE</a></td>
<td>568</td>
<td>Medium</td></tr></table></div><a name="org.quattor.ant.VOConfigTaskVOConfig"></a>
<div class="section">
<h3><a name="org.quattor.ant.VOConfigTaskVOConfig"></a>org.quattor.ant.VOConfigTask$VOConfig</h3>
<table border="0" class="bodyTable">
<tr class="b">
<th>Bug</th>
<th>Category</th>
<th>Details</th>
<th>Line</th>
<th>Priority</th></tr>
<tr class="a">
<td>org.quattor.ant.VOConfigTask$VOConfig.writeVOTemplate(String) makes inefficient use of keySet iterator instead of entrySet iterator</td>
<td>PERFORMANCE</td>
<td><a class="externalLink" href="http://findbugs.sourceforge.net/bugDescriptions.html#WMI_WRONG_MAP_ITERATOR">WMI_WRONG_MAP_ITERATOR</a></td>
<td>796</td>
<td>Medium</td></tr></table></div><a name="org.quattor.ant.VOConfigTaskVOMSEndpoint"></a>
<div class="section">
<h3><a name="org.quattor.ant.VOConfigTaskVOMSEndpoint"></a>org.quattor.ant.VOConfigTask$VOMSEndpoint</h3>
<table border="0" class="bodyTable">
<tr class="b">
<th>Bug</th>
<th>Category</th>
<th>Details</th>
<th>Line</th>
<th>Priority</th></tr>
<tr class="a">
<td>Should org.quattor.ant.VOConfigTask$VOMSEndpoint be a _static_ inner class?</td>
<td>PERFORMANCE</td>
<td><a class="externalLink" href="http://findbugs.sourceforge.net/bugDescriptions.html#SIC_INNER_SHOULD_BE_STATIC">SIC_INNER_SHOULD_BE_STATIC</a></td>
<td>815</td>
<td>Medium</td></tr></table></div><a name="org.quattor.ant.VOConfigTaskVOMSServer"></a>
<div class="section">
<h3><a name="org.quattor.ant.VOConfigTaskVOMSServer"></a>org.quattor.ant.VOConfigTask$VOMSServer</h3>
<table border="0" class="bodyTable">
<tr class="b">
<th>Bug</th>
<th>Category</th>
<th>Details</th>
<th>Line</th>
<th>Priority</th></tr>
<tr class="a">
<td>Redundant nullcheck of certValue, which is known to be non-null in org.quattor.ant.VOConfigTask$VOMSServer.setOldCert(String)</td>
<td>STYLE</td>
<td><a class="externalLink" href="http://findbugs.sourceforge.net/bugDescriptions.html#RCN_REDUNDANT_NULLCHECK_OF_NONNULL_VALUE">RCN_REDUNDANT_NULLCHECK_OF_NONNULL_VALUE</a></td>
<td>987</td>
<td>Medium</td></tr></table></div><a name="org.quattor.ant.VOConfigTaskVOMSServerCertificate"></a>
<div class="section">
<h3><a name="org.quattor.ant.VOConfigTaskVOMSServerCertificate"></a>org.quattor.ant.VOConfigTask$VOMSServerCertificate</h3>
<table border="0" class="bodyTable">
<tr class="b">
<th>Bug</th>
<th>Category</th>
<th>Details</th>
<th>Line</th>
<th>Priority</th></tr>
<tr class="a">
<td>Should org.quattor.ant.VOConfigTask$VOMSServerCertificate be a _static_ inner class?</td>
<td>PERFORMANCE</td>
<td><a class="externalLink" href="http://findbugs.sourceforge.net/bugDescriptions.html#SIC_INNER_SHOULD_BE_STATIC">SIC_INNER_SHOULD_BE_STATIC</a></td>
<td>1110</td>
<td>Medium</td></tr></table>

**Comment by DChambersSTFC** [comment]
All reported issues fixed and merged.
